kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
org.gradle.jvmargs=-Xmx8192m
project.version=0.0.1
project.group=io.github.kshulzh.kefir
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
kotlin.daemon.debug.log=true